// Copyright Epic Games, Inc. All Rights Reserved.

#include "GameSetting.h"
#include "Framework/Text/ITextDecorator.h"
#include "Framework/Text/RichTextMarkupProcessing.h"
#include "Engine/LocalPlayer.h"
#include "HAL/IConsoleManager.h"

#include UE_INLINE_GENERATED_CPP_BY_NAME(GameSetting)

#define LOCTEXT_NAMESPACE "GameSetting"

#define UE_CAN_SHOW_SETTINGS_DEBUG_INFO (!UE_BUILD_SHIPPING)

namespace GameSettingsConsoleVars
{
#if UE_CAN_SHOW_SETTINGS_DEBUG_INFO
	// 控制动态详情是否显示开发者名称和类名：-1 自动、0 关闭、1 强制开启。
	int32 ShowDebugInfoMode = -1;

	// 将调试显示模式暴露为 GameSettings.ShowDebugInfo 控制台变量。
	static FAutoConsoleVariableRef CVarGameSettingsShowDebugInfo(
		TEXT("GameSettings.ShowDebugInfo"),
		ShowDebugInfoMode,
		TEXT("Should we show the developer name and class as part of dynamic details?\n")
		TEXT("  -1: Default (enabled in editor, disabled in -game or cooked builds)\n")
		TEXT("   0: Never show it\n")
		TEXT("   1: Always show it\n")
		TEXT("\n")
		TEXT("  Note: Shipping builds always disable this"),
		ECVF_Default);
#endif
}


// 设置基类实现初始化、就绪、可编辑状态缓存、依赖刷新和事件广播。
//--------------------------------------
// UGameSetting
//--------------------------------------

// 绑定所属本地玩家，初始化编辑条件与所有子设置，然后进入设置启动流程；重复传入同一玩家时直接返回。
void UGameSetting::Initialize(ULocalPlayer* InLocalPlayer)
{
	// 如果已经保存了这个本地玩家，说明该设置已经完成初始化。
	// If we've already gotten this local player we're already initialized.
	if (LocalPlayer == InLocalPlayer)
	{
		return;
	}

	LocalPlayer = InLocalPlayer;

	//TODO: GameSettings
	//LocalPlayer->OnPlayerLoggedIn().AddUObject(this, &UGameSetting::RefreshEditableState, true);

#if !UE_BUILD_SHIPPING
	ensureAlwaysMsgf(DevName != NAME_None, TEXT("You must provide a DevName for the setting."));
	ensureAlwaysMsgf(!DisplayName.IsEmpty(), TEXT("You must provide a DisplayName for settings."));
#endif

	for (const TSharedRef<FGameSettingEditCondition>& EditCondition : EditConditions)
	{
		EditCondition->Initialize(LocalPlayer);
	}

	// 如果该设置包含子设置，也一并使用同一本地玩家初始化。
	// If there are any child settings go ahead and initialize them as well.
	for (UGameSetting* Setting : GetChildSettings())
	{
		Setting->Initialize(LocalPlayer);
	}

	Startup();
}

// 启动设置的就绪流程；基类无需异步准备，因此立即标记启动完成。
void UGameSetting::Startup()
{
	StartupComplete();
}

// 把设置标记为可安全使用，调用初始化扩展点并广播就绪事件。
void UGameSetting::StartupComplete()
{
	ensureMsgf(!bReady, TEXT("StartupComplete called twice."));

	if (!bReady)
	{
		bReady = true;
		OnInitialized();
	}
}

// 提交当前设置：调用派生类应用扩展点，并广播已应用事件供注册表和界面响应。
void UGameSetting::Apply()
{
	OnApply();

	// 遍历所有编辑条件，通知它们重新评估状态。
	// Run through any edit conditions and let them know things changed.
	for (const TSharedRef<FGameSettingEditCondition>& EditCondition : EditConditions)
	{
		EditCondition->SettingApplied(LocalPlayer, this);
	}

	OnSettingAppliedEvent.Broadcast(this);
}

// 确认启动流程已经完成，并计算第一份可编辑状态缓存供界面直接读取。
void UGameSetting::OnInitialized()
{
	ensureMsgf(bReady, TEXT("OnInitialized called directly instead of via StartupComplete."));
	EditableStateCache = ComputeEditableState();
}

// 提供实际提交设置的派生类扩展点；基类不附加处理。
void UGameSetting::OnApply()
{
	// 默认不执行额外操作。
	// No-Op by default.
}

// 返回所属本地玩家的当前世界；玩家无效时返回空指针。
UWorld* UGameSetting::GetWorld() const
{
	return LocalPlayer ? LocalPlayer->GetWorld() : nullptr;
}

// 记录设置父级，并校验不会重复挂接到不同容器。
void UGameSetting::SetSettingParent(UGameSetting* InSettingParent)
{
	SettingParent = InSettingParent;
}

// 汇总设置自身规则、编辑条件和当前过滤状态，生成缓存用的可见与可编辑状态。
FGameSettingEditableState UGameSetting::ComputeEditableState() const
{
	FGameSettingEditableState EditState;

	// 先收集设置自身定义的特殊编辑规则。
	// Does this setting itself have any special rules?
	OnGatherEditState(EditState);

	// 再遍历附加的编辑条件。
	// Run through any edit conditions
	for (const TSharedRef<FGameSettingEditCondition>& EditCondition : EditConditions)
	{
		EditCondition->GatherEditState(LocalPlayer, EditState);
	}

	return EditState;
}

// 允许派生设置向可编辑状态追加自身约束；基类不添加限制。
void UGameSetting::OnGatherEditState(FGameSettingEditableState& InOutEditState) const
{

}

// 确保搜索文本缓存有效后返回纯文本说明。
const FString& UGameSetting::GetDescriptionPlainText() const
{
	RefreshPlainText();
	return AutoGenerated_DescriptionPlainText;
}

// 在缓存失效时把富文本说明转换为纯文本，并按当前语言文化重新生成搜索内容。
void UGameSetting::RefreshPlainText() const
{
	// TODO：GameSettings 在语言变化后需要重新生成可搜索文本缓存。
	//TODO: GameSettings
	// TODO NDarnell Settings - Will need to recache if the language changes.

	if (bRefreshPlainSearchableText)
	{
		TArray<FTextLineParseResults> ActualResultsArray;
		FString ActualOutput;
		FDefaultRichTextMarkupParser::GetStaticInstance()->Process(ActualResultsArray, DescriptionRichText.ToString(), ActualOutput);

		AutoGenerated_DescriptionPlainText.Reset();
		for (const FTextLineParseResults& Line : ActualResultsArray)
		{
			for (const FTextRunParseResults& Run : Line.Runs)
			{
				if (Run.Name.IsEmpty())
				{
					AutoGenerated_DescriptionPlainText.Append(ActualOutput.Mid(Run.OriginalRange.BeginIndex, Run.OriginalRange.Len()));
				}
				else if (!Run.ContentRange.IsEmpty())
				{
					AutoGenerated_DescriptionPlainText.Append(ActualOutput.Mid(Run.ContentRange.BeginIndex, Run.ContentRange.Len()));
				}
			}
		}

		bRefreshPlainSearchableText = false;
	}
}

// 防止重入地广播设置值变化，先调用本类回调，再通知外部监听者。
void UGameSetting::NotifySettingChanged(EGameSettingChangeReason Reason)
{
	OnSettingChanged(Reason);
	
	// 遍历所有编辑条件，通知它们重新评估状态。
	// Run through any edit conditions and let them know things changed.
	for (const TSharedRef<FGameSettingEditCondition>& EditCondition : EditConditions)
	{
		EditCondition->SettingChanged(LocalPlayer, this, Reason);
	}

	if (!bOnSettingChangedEventGuard)
	{
		TGuardValue<bool> Guard(bOnSettingChangedEventGuard, true);
		OnSettingChangedEvent.Broadcast(this, Reason);
	}
}

// 提供设置值变化后的派生类扩展点；基类不附加处理。
void UGameSetting::OnSettingChanged(EGameSettingChangeReason Reason)
{
	// 该基类默认不执行额外操作，交由派生类按需覆盖。
	// No-Op
}

// 附加编辑条件并在设置已初始化时立即初始化该条件，随后刷新可编辑状态。
void UGameSetting::AddEditCondition(const TSharedRef<FGameSettingEditCondition>& InEditCondition)
{
	EditConditions.Add(InEditCondition);

	InEditCondition->OnEditConditionChangedEvent.AddUObject(this, &ThisClass::RefreshEditableState);
}

// 订阅依赖设置的值与编辑状态变化，使当前设置在依赖变化后重新评估。
void UGameSetting::AddEditDependency(UGameSetting* DependencySetting)
{
	if (ensure(DependencySetting))
	{
		DependencySetting->OnSettingChangedEvent.AddUObject(this, &ThisClass::HandleEditDependencyChanged);
		DependencySetting->OnSettingEditConditionChangedEvent.AddUObject(this, &ThisClass::HandleEditDependencyChanged);
	}
}

// 本地玩家有效时重新计算并缓存可编辑状态，可选地通知各编辑条件及界面监听者。
void UGameSetting::RefreshEditableState(bool bNotifyEditConditionsChanged)
{
	// 本地玩家可能先于设置对象销毁；发生这种情况时必须忽略可编辑状态刷新请求。
	// The LocalPlayer may be destroyed out from under us, if that happens,
	// we need to ignore attempts to refresh the editable state.
	if (!LocalPlayer)
	{
		return;
	}

	//TODO: GameSettings
	//// We should wait until the player is fully logged in before trying to refresh settings.
	//if (!LocalPlayer->IsLoggedIn())
	//{
	//	return;
	//}

	if (!bOnEditConditionsChangedEventGuard)
	{
		TGuardValue<bool> Guard(bOnEditConditionsChangedEventGuard, true);
	
		EditableStateCache = ComputeEditableState();

		if (bNotifyEditConditionsChanged)
		{
			NotifyEditConditionsChanged();
		}		
	}
}

// 防止重入地广播编辑条件变化，使依赖设置和当前界面同步刷新。
void UGameSetting::NotifyEditConditionsChanged()
{
	OnEditConditionsChanged();

	OnSettingEditConditionChangedEvent.Broadcast(this);
}

// 提供编辑条件变化后的派生类扩展点；基类不附加处理。
void UGameSetting::OnEditConditionsChanged()
{

}

// 接收依赖设置变化；忽略具体来源后统一触发当前设置的依赖更新扩展点。
void UGameSetting::HandleEditDependencyChanged(UGameSetting* DependencySetting)
{
	OnDependencyChanged();
	RefreshEditableState();
}

// 接收依赖设置变化；忽略具体来源后统一触发当前设置的依赖更新扩展点。
void UGameSetting::HandleEditDependencyChanged(UGameSetting* DependencySetting, EGameSettingChangeReason Reason)
{
	OnDependencyChanged();
	RefreshEditableState();

	if (Reason != EGameSettingChangeReason::DependencyChanged)
	{
		NotifySettingChanged(EGameSettingChangeReason::DependencyChanged);
	}
}

// 依赖设置变化后重新计算当前设置的可编辑状态。
void UGameSetting::OnDependencyChanged()
{

}

// 组合派生类动态详情、外部详情回调与调试信息，返回详情面板最终显示文本。
FText UGameSetting::GetDynamicDetails() const
{
	if (!LocalPlayer)
	{
		return FText::GetEmpty();
	}

	FText DynamicDetailsText = DynamicDetails.IsBound() ? DynamicDetails.Execute(*LocalPlayer) : FText::GetEmpty();
	
#if UE_CAN_SHOW_SETTINGS_DEBUG_INFO
	if ((GameSettingsConsoleVars::ShowDebugInfoMode == 1) || ((GameSettingsConsoleVars::ShowDebugInfoMode == -1) && GIsEditor))
	{
		const FString DevSettingDetails = FString::Printf(TEXT("%s<debug>DevName: %s</>\n<debug>Class: %s</>"),
			DynamicDetailsText.IsEmpty() ? TEXT("") : TEXT("\n"),
			*DevName.ToString(),
			*GetClass()->GetName());

		DynamicDetailsText = FText::Format(LOCTEXT("DevDynamicDetailsFormat", "{0}{1}"),
			DynamicDetailsText,
			FText::FromString(DevSettingDetails));
	}
#endif

	return DynamicDetailsText;
}

// 提供派生类生成动态详情的扩展点；基类返回空文本。
FText UGameSetting::GetDynamicDetailsInternal() const
{
	return FText::GetEmpty();
}

// 记录当前语言文化并立即生成字符串缓存，后续仅在失效或文化变化时重算。
UGameSetting::FStringCultureCache::FStringCultureCache(TFunction<FString()> InStringGetter)
	: Culture(FInternationalization::Get().GetCurrentCulture())
	, StringGetter(InStringGetter)
{
	StringCache = StringGetter();
}

// 清空缓存的语言文化标识，使下次读取重新生成字符串。
void UGameSetting::FStringCultureCache::Invalidate()
{
	StringCache = StringGetter();
	Culture = FInternationalization::Get().GetCurrentCulture();
}

// 仅在缓存失效或语言文化改变时调用字符串生成器，否则直接返回缓存内容。
FString UGameSetting::FStringCultureCache::Get() const
{
	if (Culture == FInternationalization::Get().GetCurrentCulture())
	{
		return StringCache;
	}

	StringCache = StringGetter();
	Culture = FInternationalization::Get().GetCurrentCulture();

	return StringCache;
}

#undef LOCTEXT_NAMESPACE

