// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once


#if COMMONUSER_OSSV1

// Online Subsystem（OSS v1）分支所需的包含文件与前置声明。
// Online Subsystem (OSS v1) includes and forward declares
#include "OnlineSubsystemTypes.h"
class IOnlineSubsystem;
struct FOnlineError;
using FOnlineErrorType = FOnlineError;
using ELoginStatusType = ELoginStatus::Type;

#else

// Online Services（OSS v2）分支所需的包含文件与前置声明。
// Online Services (OSS v2) includes and forward declares
#include "Online/Connectivity.h"
#include "Online/OnlineError.h"
namespace UE::Online
{
	enum class ELoginStatus : uint8;
	enum class EPrivilegeResults : uint32;
	enum class EUserPrivileges : uint8;
	using IAuthPtr = TSharedPtr<class IAuth>;
	using IOnlineServicesPtr = TSharedPtr<class IOnlineServices>;
	template <typename OpType>
	class TOnlineResult;
	struct FAuthLogin;
	struct FConnectionStatusChanged;
	struct FExternalUIShowLoginUI;
	struct FAuthLoginStatusChanged;
	struct FQueryUserPrivilege;
	struct FAccountInfo;
}
using FOnlineErrorType = UE::Online::FOnlineError;
using ELoginStatusType = UE::Online::ELoginStatus;

#endif

#include "CommonUserTypes.generated.h"


/** 指定在线查询应使用哪个后端上下文以及如何回退的枚举。 */
/** Enum specifying where and how to run online queries */
UENUM(BlueprintType)
enum class ECommonUserOnlineContext : uint8
{
	/** 游戏代码使用的聚合上下文；以默认系统为基础，并可对多个后端上下文的结果执行特殊合并。 */
	/** Called from game code, this uses the default system but with special handling that could merge results from multiple contexts */
	Game,

	/** 引擎默认在线系统，始终存在，并与 Service 或 Platform 中的一个相同。 */
	/** The default engine online system, this will always exist and will be the same as either Service or Platform */
	Default,
	
	/** 明确请求外部在线服务；该服务可能不存在。 */
	/** Explicitly ask for the external service, which may not exist */
	Service,

	/** 优先使用外部在线服务，不可用时回退到默认系统。 */
	/** Looks for external service first, then falls back to default */
	ServiceOrDefault,
	
	/** 明确请求平台在线系统；该系统可能不存在。 */
	/** Explicitly ask for the platform system, which may not exist */
	Platform,

	/** 优先使用平台在线系统，不可用时回退到默认系统。 */
	/** Looks for platform system first, then falls back to default */
	PlatformOrDefault,

	/** 无效的在线系统上下文。 */
	/** Invalid system */
	Invalid
};

/** 描述指定用户在本地身份获取和在线登录流程中所处阶段的枚举。 */
/** Enum describing the state of initialization for a specific user */
UENUM(BlueprintType)
enum class ECommonUserInitializationState : uint8
{
	/** 用户尚未开始登录流程。 */
	/** User has not started login process */
	Unknown,

	/** 玩家正在通过本地登录获取平台用户标识。 */
	/** Player is in the process of acquiring a user id with local login */
	DoingInitialLogin,

	/** 玩家已完成本地登录，正在执行在线后端登录。 */
	/** Player is performing the network login, they have already logged in locally */
	DoingNetworkLogin,

	/** 玩家未能完成任何可用登录。 */
	/** Player failed to log in at all */
	FailedtoLogin,

	
	/** 玩家已在线登录并可使用在线功能。 */
	/** Player is logged in and has access to online functionality */
	LoggedInOnline,

	/** 玩家已以访客或真实用户完成本地登录，但不能执行在线操作。 */
	/** Player is logged in locally (either guest or real user), but cannot perform online actions */
	LoggedInLocalOnly,


	/** 无效状态或无效用户。 */
	/** Invalid state or user */
	Invalid,
};

/** 指定用户可能拥有的游戏权限和在线能力。 */
/** Enum specifying different privileges and capabilities available to a user */
UENUM(BlueprintType)
enum class ECommonUserPrivilege : uint8
{
	/** 用户是否可以进入游戏，无论在线还是离线。 */
	/** Whether the user can play at all, online or offline */
	CanPlay,

	/** 用户是否可以参与在线游戏模式。 */
	/** Whether the user can play in online modes */
	CanPlayOnline,

	/** 用户是否可以使用在线文字聊天。 */
	/** Whether the user can use text chat */
	CanCommunicateViaTextOnline,

	/** 用户是否可以使用在线语音聊天。 */
	/** Whether the user can use voice chat */
	CanCommunicateViaVoiceOnline,

	/** 用户是否可以访问其他用户生成的内容。 */
	/** Whether the user can access content generated by other users */
	CanUseUserGeneratedContent,

	/** 用户是否具备参与跨平台联机的账户资格。 */
	/** Whether the user can ever participate in cross-play */
	CanUseCrossPlay,

	/** 无效权限，同时作为有效权限枚举数量。 */
	/** Invalid privilege (also the count of valid ones) */
	Invalid_Count					UMETA(Hidden)
};

/** 汇总多个来源后，表示功能或权限总体可用性的枚举。 */
/** Enum specifying the general availability of a feature or privilege, this combines information from multiple sources */
UENUM(BlueprintType)
enum class ECommonUserAvailability : uint8
{
	/** 状态完全未知，需要发起查询。 */
	/** State is completely unknown and needs to be queried */
	Unknown,

	/** 功能当前可以完整使用。 */
	/** This feature is fully available for use right now */
	NowAvailable,

	/** 完成正常登录流程后可能可用。 */
	/** This might be available after the completion of normal login procedures */
	PossiblyAvailable,

	/** 因网络连接等临时条件当前不可用，但本次运行稍后可能恢复。 */
	/** This feature is not available now because of something like network connectivity but may be available in the future */
	CurrentlyUnavailable,

	/** 因账户或平台的硬性限制，本次会话剩余时间内始终不可用。 */
	/** This feature will never be available for the rest of this session due to hard account or platform restrictions */
	AlwaysUnavailable,

	/** 无效功能或可用性值。 */
	/** Invalid feature */
	Invalid,
};

/** 给出用户能否使用指定权限的具体原因。 */
/** Enum giving specific reasons why a user may or may not use a certain privilege */
UENUM(BlueprintType)
enum class ECommonUserPrivilegeResult : uint8
{
	/** 权限状态未知，需要查询。 */
	/** State is unknown and needs to be queried */
	Unknown,

	/** 权限当前完全可用。 */
	/** This privilege is fully available for use */
	Available,

	/** 用户尚未完成所需登录。 */
	/** User has not fully logged in */
	UserNotLoggedIn,

	/** 用户没有游戏或相关内容的有效许可证。 */
	/** User does not own the game or content */
	LicenseInvalid,

	/** 游戏需要更新或安装补丁后才能使用该权限。 */
	/** The game needs to be updated or patched before this will be available */
	VersionOutdated,

	/** 当前没有网络连接，重新连接后可能恢复。 */
	/** No network connection, this may be resolved by reconnecting */
	NetworkConnectionUnavailable,

	/** 受到年龄分级或家长控制限制。 */
	/** Parental control failure */
	AgeRestricted,

	/** 账户缺少所需订阅或账户类型。 */
	/** Account does not have a required subscription or account type */
	AccountTypeRestricted,

	/** 账户受到其他限制，例如被在线服务封禁。 */
	/** Another account/user restriction such as being banned by the service */
	AccountUseRestricted,

	/** 其他平台特定失败。 */
	/** Other platform-specific failure */
	PlatformFailure,
};

/** 跟踪不同异步操作执行进度的内部状态枚举。 */
/** Used to track the progress of different asynchronous operations */
enum class ECommonUserAsyncTaskState : uint8
{
	/** 任务尚未开始。 */
	/** The task has not been started */
	NotStarted,
	/** 任务正在处理中。 */
	/** The task is currently being processed */
	InProgress,
	/** 任务已成功完成。 */
	/** The task has completed successfully */
	Done,
	/** 任务未能完成。 */
	/** The task failed to complete */
	Failed
};

/** 可供蓝图读取的在线操作结果详情，本质上是 FOnlineError 的稳定包装。 */
/** Detailed information about the online error. Effectively a wrapper for FOnlineError. */
USTRUCT(BlueprintType)
struct FOnlineResultInformation
{
	GENERATED_BODY()

	/** 操作是否成功；成功时其余错误字段不包含附加信息。 */
	/** Whether the operation was successful or not. If it was successful, the error fields of this struct will not contain extra information. */
	UPROPERTY(BlueprintReadOnly)
	bool bWasSuccessful = true;

	/** 唯一错误标识，可用于匹配调用方专门处理的错误。 */
	/** The unique error id. Can be used to compare against specific handled errors. */
	UPROPERTY(BlueprintReadOnly)
	FString ErrorId;

	/** 适合向用户显示的本地化错误文本。 */
	/** Error text to display to the user. */
	UPROPERTY(BlueprintReadOnly)
	FText ErrorText;

	/**
	 * 使用 FOnlineErrorType 填充成功状态、错误标识和显示文本。
	 * @param InOnlineError 要转换的在线错误。
	 */
	/**
	 * Initialize this from an FOnlineErrorType
	 * @param InOnlineError the online error to initialize from
	 */
	void COMMONUSER_API FromOnlineError(const FOnlineErrorType& InOnlineError);
};
